### ISSUE TITLE
A shared buffer instead of generating a new Vec every time

### ISSUE THREAD

**Issue by Arnavion** [mmstick/permutate#1]
The current `Iterator::next` impl returns a new `Vec` for every iteration.

It would be nice if there was also an API like `fn next(output: &mut [T]) -> bool` that populated the given output buffer with the values of the next iteration, and returned false at the end of iteration.

The closest analogy to this in the stdlib is `std::io::Read::read`, although that's only for `u8` buffers.

**Comment by mmstick** [comment]
I'll add such a feature to compliment the existing `Iterator` trait. I won't be able to call the method `next()` though because that's taken by the `Iterator` trait. I'll make it so that a good usage is to use the `next()` method to allocate the first `Vec`, and then a new `next_with_buffer(&mut buffer)` method will allow re-using that buffer, or simply ignoring the built-in `Iterator` trait and use `next_with_buffer()` with your own buffer.

**Comment by mmstick** [comment]
[Done](https://github.com/mmstick/permutate/commit/749e52e8fd6cfecfdbf1f9acfc4aee757c99f143)
